Added check for if systemd is installed

diff --git a/source_code/uninstall b/source_code/uninstall
--- a/source_code/uninstall
+++ b/source_code/uninstall
@@ -1,4 +1,8 @@
 #!/bin/bash
+if ! which systemd > /dev/null; then
+	echo "You don't have systemd installed, this can't be installed!"
+	exit 1
+fi
 sudo systemctl disable bootTuner
 sudo rm /usr/lib/systemd/scripts/bootTuner
 sudo rm /usr/lib/systemd/system/bootTuner.service
